listone=['IBM','APPLE','TESLA','APPLE',]
print('List one is ',listone)
print('Add Amazon at the end')
listone.append('AMAZON')
print('List one is ',listone)
print('Sorted the list')
listone.sort()
print('List one is ',listone)
print("Apple count is ",listone.count('APPLE'))
print('Remove APPLE')
listone.remove('APPLE')
print('List one is ',listone)
print('Copy listone to mylist')
mylist=listone.copy()
print('mylist is ',mylist)
listtwo=[27,89,90,290]
print('new list is ',listtwo)
print('Join two list')
print(listone + listtwo)
